services:
  server:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - POSTGRES_PASSWORD=mysecretpassword
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_custom_network
    command: flask run --host=0.0.0.0

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt